dotenv: .env
dependencies:
  # -<organization/repo/chainlink-brownie-contract@1.1.1>
  - "smartcontractkit/chainlink-brownie-contracts@0.4.0"
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
